import Foundation
import SwiftData

/// A practice session — generated by `SessionGenerator`, persisted as the user
/// works through it, and used by the engine to learn over time.
@Model
final class PracticeSession {

    @Attribute(.unique) var id: UUID

    var createdAt: Date
    var completedAt: Date?

    /// User inputs at generation time.
    var facilityRaw: String
    var clubsRaw: [String]
    var targetMinutes: Int

    /// Snapshot of the skill means at the time of generation,
    /// stored as compact JSON so we can graph improvement.
    var skillMeansSnapshotJSON: String

    /// Ordered list of planned drills (records). SwiftData cascades on delete.
    @Relationship(deleteRule: .cascade, inverse: \DrillRecord.session)
    var drills: [DrillRecord] = []

    init(facility: Facility,
         clubs: Set<ClubCategory>,
         targetMinutes: Int,
         skillMeans: [SkillArea: Double]) {
        self.id = UUID()
        self.createdAt = Date()
        self.facilityRaw = facility.rawValue
        self.clubsRaw = clubs.map(\.rawValue).sorted()
        self.targetMinutes = targetMinutes
        self.skillMeansSnapshotJSON = Self.encodeSnapshot(skillMeans)
    }

    var facility: Facility {
        Facility(rawValue: facilityRaw) ?? .fullFacility
    }

    var clubs: Set<ClubCategory> {
        Set(clubsRaw.compactMap { ClubCategory(rawValue: $0) })
    }

    var isCompleted: Bool { completedAt != nil }

    /// Sorted by `order`.
    var orderedDrills: [DrillRecord] {
        drills.sorted { $0.order < $1.order }
    }

    /// Sum of planned minutes across all drills.
    var plannedMinutes: Int {
        drills.reduce(0) { $0 + $1.plannedMinutes }
    }

    /// How many drills have been rated.
    var completedDrillCount: Int {
        drills.filter { $0.rating != nil }.count
    }

    // MARK: - Snapshot helpers

    private static func encodeSnapshot(_ means: [SkillArea: Double]) -> String {
        let dict = means.reduce(into: [String: Double]()) { acc, kv in
            acc[kv.key.rawValue] = kv.value
        }
        guard let data = try? JSONEncoder().encode(dict),
              let s = String(data: data, encoding: .utf8) else {
            return "{}"
        }
        return s
    }

    func decodeSnapshot() -> [SkillArea: Double] {
        guard let data = skillMeansSnapshotJSON.data(using: .utf8),
              let raw = try? JSONDecoder().decode([String: Double].self, from: data) else {
            return [:]
        }
        var result: [SkillArea: Double] = [:]
        for (k, v) in raw {
            if let skill = SkillArea(rawValue: k) { result[skill] = v }
        }
        return result
    }
}
