import Foundation
import SwiftData

/// A practice session — generated by `SessionGenerator`, persisted as the user
/// works through it, and used by the engine to learn over time.
@Model
final class PracticeSession {

    @Attribute(.unique) var id: UUID

    var createdAt: Date
    var completedAt: Date?

    /// User inputs at generation time.
    var facilityRaw: String
    var clubBucketsRaw: [String]
    var targetMinutes: Int

    /// Ordered list of planned drills. SwiftData cascades on delete.
    @Relationship(deleteRule: .cascade, inverse: \DrillRecord.session)
    var drills: [DrillRecord] = []

    init(facility: Facility,
         clubBuckets: Set<ClubBucket>,
         targetMinutes: Int) {
        self.id = UUID()
        self.createdAt = Date()
        self.facilityRaw = facility.rawValue
        self.clubBucketsRaw = clubBuckets.map(\.rawValue).sorted()
        self.targetMinutes = targetMinutes
    }

    var facility: Facility {
        Facility(rawValue: facilityRaw) ?? .fullFacility
    }

    var clubBuckets: Set<ClubBucket> {
        Set(clubBucketsRaw.compactMap { ClubBucket(rawValue: $0) })
    }

    var isCompleted: Bool { completedAt != nil }

    /// Sorted by `order`.
    var orderedDrills: [DrillRecord] {
        drills.sorted { $0.order < $1.order }
    }

    /// How many drills have been rated.
    var completedDrillCount: Int {
        drills.filter { $0.rating != nil }.count
    }
}
